# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d0dd143297c46851cd6e20ba1f14af52eb20be6fb24d62ecfa8128e75f22a698e6b8c0c8900e6d668e3e0fce406e9bd3ccb57ef9a31831033b886e1cc9e91d

test:
  secret_key_base: 241f12f4e18a97d59d48b1d5bcb7a5d565d85df306d4a3409095a7cdc27f11c1fe993e4344839165e90d74c80efc050cf441f7af5cdc8653e616396464050908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
